/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import javax.swing.JOptionPane;


/**
 *
 * @author sumiya
 */
public class SingUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SingUpFrame
     */
    public SingUpFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_oname = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        label_usertype = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        text_oname = new javax.swing.JTextField();
        text_email = new javax.swing.JTextField();
        label_singup = new javax.swing.JLabel();
        btn_signup = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(204, 153, 0));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_oname.setText("Organization Name:");
        jPanel1.add(label_oname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        label_email.setText("E-mail:");
        jPanel1.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        label_password.setText("Password:");
        jPanel1.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        label_usertype.setText("UserType:");
        jPanel1.add(label_usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));
        jPanel1.add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 200, -1));

        text_oname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_onameActionPerformed(evt);
            }
        });
        jPanel1.add(text_oname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, -1));
        jPanel1.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, -1));

        label_singup.setText("SIGN UP!");
        jPanel1.add(label_singup, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btn_signup.setText("sign up");
        btn_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signupMouseClicked(evt);
            }
        });
        jPanel1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usertype 1", "usertype 2" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 200, -1));

        panel_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 440, 490));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_onameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_onameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_onameActionPerformed

    private void btn_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signupMouseClicked
        // TODO add your handling code here:
        String o_name = text_oname.getText(); // Get the username entered by the user
        String password = new String(text_password.getPassword()); // Get the password entered by the user

        // Perform signup logic
        if (performSignup(o_name, password)) {
            // Successful signup
            JOptionPane.showMessageDialog(this, "Signup successful!");
            openLoginPage();
            //saveSignupData()
        } else {
            // Failed signup
            JOptionPane.showMessageDialog(this, "Signup failed", "Signup Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_signupMouseClicked
    
    private boolean performSignup(String o_name, String password) {
        // Here you can implement your own signup logic.
        // For demonstration purposes, let's assume the signup is successful if the username and password are not empty.
        return !o_name.isEmpty() && !password.isEmpty();
    }

    private void openLoginPage() {
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        this.dispose(); // Close the current frame (signup or login frame)
    }
    

// ...

// Close the login frame
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_oname;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_singup;
    private javax.swing.JLabel label_usertype;
    private javax.swing.JPanel panel_main;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_oname;
    private javax.swing.JPasswordField text_password;
    // End of variables declaration//GEN-END:variables
}
